server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/portfolios/**
        - id: goal-service
          uri: lb://goal-service
          predicates:
            - Path=/api/goals/**
        - id: cashflow-service
          uri: lb://cashflow-service
          predicates:
            - Path=/api/cashflow/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"